### PR TITLE
eselect fixes

### PR DESCRIPTION
**Pull request by xdch47**

### CODE REVIEW

**Comment by xdch47** [comment]
this is #19 without a7602d6  (which is #21).

**Comment by msva** [comment]
Don't you mind if I'll also squash (and sign by myself) your #18 too, before applying this?

Or can you do it yourself?

// return-point is https://github.com/gentoo/gentoo-zsh-completions/commit/316539d233d0a03fc8f68b9ada33583b1ab6c4d9 (and I already re-applied whubbs patch locally, so waiting for you decision on #18 and then will merge this and #21)

**Comment by xdch47** [comment]
actually, I think they are all logical independent, except of the fixes 885d07b 57c3e5b and  
the small improvement (b6d33b0), which could squash together with the inital eselect commit (45247d1).

**Comment by xdch47** [comment]
I can do that by myself or if you want something different, feel free to to squash.
what do you prefer ? i can also reopen a new PR based on c885c21d

**Comment by msva** [comment]
manually merged

(and finally synced with git.gento.org repo)

**Pull request closed without merging**
