### PR TITLE
Replace 'upgradeonly' with 'changed-use'

### LINKED ISSUE #30: emerge --upgradeonly does not exist
`--upgradeonly` is not a real flag for `emerge`, and was removed in 2006 (portage commit [dad1e45ff9829f3d359ccba4edfcd9678b53451a](https://cgit.gentoo.org/proj/portage.git/commit/?id=dad1e45ff9829f3d359ccba4edfcd9678b53451a)).

`-U` now refers to `--changed-use`, as of 2014 (portage commit [d55690aa3a1a9b4a78e87acd6ce179c17262966e](https://cgit.gentoo.org/proj/portage.git/commit/?id=d55690aa3a1a9b4a78e87acd6ce179c17262966e))

See: emerge(1), search `--changed-use`

### PR DESCRIPTION
**Pull request by gbrlsnchs**
Fixes #30.

### CODE REVIEW

**Comment by thesamesam** [comment]
@msva

**Comment by gbrlsnchs** [comment]
As a side note, I tested this PR locally by patching `gentoo-zsh-completions` using `/etc/portage/patches`.

**Comment by msva** [comment]
Looks pretty valid.
I'll test it and will merge it shortly.

**Comment by msva** [comment]
@gbrlsnchs sorry, I forgot to ask you to add Signed-off-by (`git commit -s`) as by GLEP76 https://www.gentoo.org/glep/glep-0076.html

Can you, please, re-create a PR with commit with `Signed-off-by`?

**Comment by msva** [comment]
@gbrlsnchs or, alternatively, if you don't want to sign-off, but don't mind, I can commit it on my own, and add a credit to you nd this PR in commit message.

**Comment by gbrlsnchs** [comment]
@msva No worries. Coincidentally I started signing off my commits but by the time I opened this PR I wasn't yet.

**Pull request merged**
